import { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Royal Velvet Embroidered Sherwani",
    slug: "royal-velvet-embroidered-sherwani",
    description: "Handcrafted burgundy velvet sherwani with intricate zardozi work and silk lining.",
    category: "men",
    subcategory: "Ethnic Wear",
    price: 14999,
    compare_price: 19999,
    images: [
      "https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["38", "40", "42", "44"],
    colors: [
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Gold", hex: "#C8964E" },
      { name: "Midnight Black", hex: "#1A1A1A" },
    ],
    in_stock: true,
    stock_count: 15,
    featured: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod-2",
    name: "Handwoven Banarasi Silk Saree",
    slug: "handwoven-banarasi-silk-saree",
    description: "Pure katan silk saree woven with real gold zari floral motifs and a rich pallu.",
    category: "women",
    subcategory: "Sarees",
    price: 18499,
    compare_price: 24999,
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["Free Size"],
    colors: [
      { name: "Crimson Red", hex: "#9E1B32" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Royal Emerald", hex: "#0B5345" },
    ],
    in_stock: true,
    stock_count: 8,
    featured: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod-3",
    name: "Embroidered Kurta Pyjama Set for Boys",
    slug: "boys-embroidered-kurta-pyjama-set",
    description: "Festive cotton silk kurta pyjama set with subtle thread embroidery and soft lining.",
    category: "kids",
    subcategory: "Boys Festive",
    price: 2999,
    compare_price: 3999,
    images: [
      "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["2-3 Y", "4-5 Y", "6-7 Y", "8-9 Y"],
    colors: [
      { name: "Warm Gold", hex: "#C8964E" },
      { name: "Cream", hex: "#FFF8F0" },
    ],
    in_stock: true,
    stock_count: 22,
    featured: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod-4",
    name: "Classic Linen Tailored Shirt",
    slug: "classic-linen-tailored-shirt",
    description: "Breathable European flax linen casual shirt with mother-of-pearl buttons.",
    category: "men",
    subcategory: "Casual Shirts",
    price: 3499,
    compare_price: 4499,
    images: [
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Warm Sand", hex: "#D2B48C" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Off White", hex: "#F8F9FA" },
    ],
    in_stock: true,
    stock_count: 35,
    featured: false,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod-5",
    name: "Chanderi Floral Anarkali Suit",
    slug: "chanderi-floral-anarkali-suit",
    description: "Graceful Chanderi silk Anarkali suit with organza dupatta and gota patti detailing.",
    category: "women",
    subcategory: "Suits & Sets",
    price: 9999,
    compare_price: 12999,
    images: [
      "https://images.unsplash.com/photo-1583391733975-009214734316?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Blush Rose", hex: "#E8A598" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Sage", hex: "#87A96B" },
    ],
    in_stock: true,
    stock_count: 14,
    featured: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod-6",
    name: "Girls Festive Jacquard Lehenga",
    slug: "girls-festive-jacquard-lehenga",
    description: "Lightweight woven jacquard lehenga choli with net dupatta designed for easy movement.",
    category: "kids",
    subcategory: "Girls Festive",
    price: 4499,
    compare_price: 5999,
    images: [
      "https://images.unsplash.com/photo-1621786030684-4c84770adcfb?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["3-4 Y", "5-6 Y", "7-8 Y", "9-10 Y"],
    colors: [
      { name: "Coral Gold", hex: "#F39C12" },
      { name: "Deep Ruby", hex: "#7C1D3E" },
    ],
    in_stock: true,
    stock_count: 19,
    featured: false,
    created_at: "2026-01-01T00:00:00.000Z",
  },
];

export const MOCK_REVIEWS = [
  {
    id: "rev-1",
    name: "Aarav Sharma",
    city: "New Delhi",
    rating: 5,
    comment: "The velvet sherwani quality surpassed all my expectations. The fit was bespoke perfection!",
    productName: "Royal Velvet Sherwani",
  },
  {
    id: "rev-2",
    name: "Priyanka Mehta",
    city: "Mumbai",
    rating: 5,
    comment: "Stunning Banarasi silk saree. The zari work is authentic and the fabric drape feels pure luxury.",
    productName: "Banarasi Silk Saree",
  },
  {
    id: "rev-3",
    name: "Vikram Singhania",
    city: "Jaipur",
    rating: 5,
    comment: "Raghav Garments sets a benchmark for Indian luxury fashion. Super fast delivery and premium packaging.",
    productName: "Classic Linen Shirt",
  },
];
