import { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
  // --- MEN ---
  {
    id: "prod-1",
    name: "Royal Velvet Embroidered Sherwani",
    slug: "royal-velvet-embroidered-sherwani",
    description: "Handcrafted burgundy velvet sherwani with intricate zardozi work and silk lining.",
    longDescription:
      "Crafted from plush micro-velvet, this regal sherwani features heritage zardozi needlework along the mandarin collar, cuffs, and button placket. Tailored for grand celebrations and weddings, it includes a tailored churidar and pocket square.",
    category: "men",
    subcategory: "Ethnic Wear",
    price: 14999,
    compare_price: 19999,
    images: [
      "https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["38", "40", "42", "44", "46"],
    colors: [
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Antique Gold", hex: "#C8964E" },
      { name: "Midnight Black", hex: "#1A1A1A" },
    ],
    in_stock: true,
    stock_count: 15,
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    rating: 4.9,
    reviewCount: 38,
    details: [
      "Intricate hand-embroidered zardozi and dabka work",
      "Concealed button closure with ornate metallic buttons",
      "Structured shoulder pads for a sharp, royal silhouette",
      "Accompanied by a matching churidar in dupion silk",
    ],
    fabric_care: [
      "Fabric: 100% Micro Velvet; Inner: 100% Cotton Silk",
      "Professional dry clean only",
      "Do not steam iron embroidery directly",
      "Store in breathable garment bag",
    ],
    sku: "RG-MEN-SHW-001",
    created_at: "2026-01-01T00:00:00.000Z",
    reviews: [
      {
        id: "rev-1",
        author: "Aarav Sharma",
        rating: 5,
        date: "Feb 12, 2026",
        title: "Spectacular craftsmanship!",
        comment:
          "Wore this to my brother's wedding and received non-stop compliments. The embroidery is super clean and the velvet feels ultra-premium.",
        verified: true,
        sizePurchased: "42",
      },
      {
        id: "rev-2",
        author: "Devendra Rathore",
        rating: 5,
        date: "Jan 28, 2026",
        title: "Royal look and perfect fit",
        comment: "Fits true to size with room for mobility. The silk inner lining makes it very comfortable to wear for hours.",
        verified: true,
        sizePurchased: "40",
      },
    ],
  },
  {
    id: "prod-2",
    name: "Classic Linen Tailored Kurta Shirt",
    slug: "classic-linen-tailored-kurta-shirt",
    description: "Breathable European flax linen casual short kurta shirt with mother-of-pearl buttons.",
    longDescription:
      "A modern blend of classic Indian short kurta aesthetics with European linen refinement. Perfectly tailored with a contemporary mandarin collar and curved hem for effortless elegance from day events to evening gatherings.",
    category: "men",
    subcategory: "Casual Shirts",
    price: 3499,
    compare_price: 4499,
    images: [
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Warm Sand", hex: "#D2B48C" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Off White", hex: "#F8F9FA" },
    ],
    in_stock: true,
    stock_count: 35,
    featured: false,
    isBestSeller: true,
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 42,
    details: [
      "100% pre-washed French linen for supreme softness",
      "Genuine mother-of-pearl buttons",
      "Band collar with 4-button placket",
      "Side slits for easy movement",
    ],
    fabric_care: [
      "100% Linen",
      "Gentle machine wash cold with similar colors",
      "Warm iron while damp for crisp finish",
      "Line dry in shade",
    ],
    sku: "RG-MEN-LIN-002",
    created_at: "2026-02-10T00:00:00.000Z",
  },
  {
    id: "prod-3",
    name: "Silk Blend Bandhgala Jodhpuri Suit",
    slug: "silk-blend-bandhgala-jodhpuri-suit",
    description: "Tailored charcoal silk bandhgala jacket with brass crest buttons and tapered trousers.",
    longDescription:
      "An epitome of masculine aristocracy, our Jodhpuri Bandhgala features hand-carved antiqued brass buttons, structured floating canvas construction, and clean Italian drape trousers.",
    category: "men",
    subcategory: "Suits & Sets",
    price: 18999,
    compare_price: 23999,
    images: [
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["38", "40", "42", "44"],
    colors: [
      { name: "Midnight Black", hex: "#1A1A1A" },
      { name: "Royal Navy", hex: "#1B2A4A" },
      { name: "Burgundy", hex: "#7C1D3E" },
    ],
    in_stock: true,
    stock_count: 12,
    featured: true,
    isBestSeller: false,
    isNewArrival: true,
    rating: 5.0,
    reviewCount: 19,
    details: [
      "Structured Italian silhouette with structured shoulder pads",
      "Antiqued brass crest buttons",
      "Double back vents for seating comfort",
      "Includes tailored trousers with adjustable waist tabs",
    ],
    fabric_care: [
      "Shell: 70% Raw Silk, 30% Wool; Lining: 100% Viscose",
      "Dry clean only",
    ],
    sku: "RG-MEN-BDH-003",
    created_at: "2026-02-20T00:00:00.000Z",
  },
  {
    id: "prod-4",
    name: "Raw Silk Festive Kurta Bundi Set",
    slug: "raw-silk-festive-kurta-bundi-set",
    description: "Artisanal raw silk Nehru jacket paired with cotton-silk kurta and churidar.",
    longDescription:
      "Celebrate festivals in timeless flair. This 3-piece set combines a rich textured Nehru vest (bundi) with a lightweight, breathable cotton-silk kurta and churidar.",
    category: "men",
    subcategory: "Ethnic Wear",
    price: 8999,
    compare_price: 11999,
    images: [
      "https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["38", "40", "42", "44", "46"],
    colors: [
      { name: "Mustard Gold", hex: "#D4AC0D" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Sage Green", hex: "#87A96B" },
    ],
    in_stock: true,
    stock_count: 20,
    featured: false,
    isBestSeller: false,
    isNewArrival: false,
    rating: 4.7,
    reviewCount: 25,
    details: [
      "3-piece ensemble: Bundi Jacket, Kurta & Churidar",
      "Textured raw slub silk with tonal buttons",
      "Welt chest pocket for pocket square styling",
    ],
    fabric_care: [
      "Bundi: 100% Raw Silk; Kurta: 60% Cotton, 40% Silk",
      "Dry clean recommended",
    ],
    sku: "RG-MEN-BNK-004",
    created_at: "2026-01-15T00:00:00.000Z",
  },

  // --- WOMEN ---
  {
    id: "prod-5",
    name: "Handwoven Banarasi Katan Silk Saree",
    slug: "handwoven-banarasi-silk-saree",
    description: "Pure katan silk saree woven with real gold zari floral motifs and a rich heritage pallu.",
    longDescription:
      "Handcrafted over 45 days by master weavers in Varanasi, this heirloom saree features intricate jaal work with gold zari intertwining across pure mulberry katan silk. Comes with unstitched blouse piece.",
    category: "women",
    subcategory: "Sarees",
    price: 18499,
    compare_price: 24999,
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["Free Size (5.5m + 0.8m Blouse)"],
    colors: [
      { name: "Crimson Red", hex: "#9E1B32" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Royal Emerald", hex: "#0B5345" },
    ],
    in_stock: true,
    stock_count: 8,
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    rating: 4.9,
    reviewCount: 56,
    details: [
      "Authentic Varanasi Handloom Mark certified",
      "Pure Katan Silk with kadwa gold zari weave",
      "Includes matching unstitched blouse fabric (80 cm)",
      "Heirloom finish with hand-twisted tassels",
    ],
    fabric_care: [
      "100% Pure Katan Silk",
      "Dry clean only",
      "Store wrapped in pure cotton muslin cloth",
      "Refold periodically to prevent crease wear",
    ],
    sku: "RG-WMN-SAR-005",
    created_at: "2026-01-01T00:00:00.000Z",
    reviews: [
      {
        id: "rev-3",
        author: "Priyanka Mehta",
        rating: 5,
        date: "Feb 05, 2026",
        title: "An absolute masterpiece",
        comment:
          "The sheen of the pure silk and the density of the zari work is unmatched. Worth every single rupee.",
        verified: true,
        sizePurchased: "Free Size",
      },
    ],
  },
  {
    id: "prod-6",
    name: "Chanderi Floral Anarkali Suit Set",
    slug: "chanderi-floral-anarkali-suit",
    description: "Graceful Chanderi silk Anarkali suit with organza dupatta and gota patti detailing.",
    longDescription:
      "A vision in pastel poetry, this flared Chanderi Anarkali features hand-block floral prints accented with delicate gold gota patti and sequins. Paired with comfortable churidar pants and a sheer scalloped organza dupatta.",
    category: "women",
    subcategory: "Suits & Sets",
    price: 9999,
    compare_price: 12999,
    images: [
      "https://images.unsplash.com/photo-1583391733975-009214734316?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Blush Rose", hex: "#E8A598" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Sage Green", hex: "#87A96B" },
    ],
    in_stock: true,
    stock_count: 14,
    featured: true,
    isBestSeller: true,
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 31,
    details: [
      "24-kali flared Anarkali silhouette with full cotton lining",
      "Scalloped hand-embroidered organza dupatta (2.5m)",
      "Comfortable elasticated waistband churidar pants",
      "Keyhole back neck with handcrafted latkan tassels",
    ],
    fabric_care: [
      "Kurta: Chanderi Silk; Lining: 100% Mulmul Cotton",
      "Dupatta: Pure Organza",
      "Dry clean only",
    ],
    sku: "RG-WMN-ANK-006",
    created_at: "2026-01-10T00:00:00.000Z",
  },
  {
    id: "prod-7",
    name: "Zari Embroidered Raw Silk Bridal Lehenga",
    slug: "zari-embroidered-raw-silk-bridal-lehenga",
    description: "Heirloom bridal lehenga in crimson raw silk with heavy antique zardozi embroidery and dual dupattas.",
    longDescription:
      "Designed for the regal bride, this masterpiece features 16 kalis intricately hand-embroidered with peacock and floral motifs using antique dabka and sequins. Complemented by a sweetheart neck blouse and double dupattas.",
    category: "women",
    subcategory: "Lehengas",
    price: 49999,
    compare_price: 64999,
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["S", "M", "L", "Custom Tailored"],
    colors: [
      { name: "Crimson Red", hex: "#9E1B32" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Deep Maroon", hex: "#4A0E17" },
    ],
    in_stock: true,
    stock_count: 5,
    featured: true,
    isBestSeller: false,
    isNewArrival: true,
    rating: 5.0,
    reviewCount: 14,
    details: [
      "Heavy hand-embroidered raw silk skirt with double can-can lining",
      "Includes padded sweetheart neck blouse with back dori tie-up",
      "Dual dupattas: 1 Velvet shoulder drape + 1 lightweight Net head veil",
      "Pocket hidden in lehenga skirt seam",
    ],
    fabric_care: [
      "Pure Raw Silk & Micro Velvet",
      "Professional bridal dry clean only",
    ],
    sku: "RG-WMN-LHG-007",
    created_at: "2026-02-14T00:00:00.000Z",
  },
  {
    id: "prod-8",
    name: "Embroidered Georgette Festive Kurti",
    slug: "embroidered-georgette-festive-kurti",
    description: "Chic Lucknowi Chikankari georgette straight kurti with pearl embellishments.",
    longDescription:
      "A versatile everyday luxury piece. Delicately hand-embroidered with traditional Lucknowi Chikankari stitches on soft flowing faux georgette, perfect for intimate celebrations or office festive days.",
    category: "women",
    subcategory: "Kurtis",
    price: 2899,
    compare_price: 3999,
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1583391733975-009214734316?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Dusty Peach", hex: "#F5CBA7" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Ivory", hex: "#FFFDF9" },
    ],
    in_stock: true,
    stock_count: 28,
    featured: false,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 18,
    details: [
      "Handcrafted shadow work and bakhia Chikankari embroidery",
      "Includes separate matching cotton inner slip",
      "Calf length straight silhouette with side slits",
    ],
    fabric_care: ["Faux Georgette", "Hand wash cold or gentle machine wash in laundry mesh"],
    sku: "RG-WMN-KRT-008",
    created_at: "2026-02-01T00:00:00.000Z",
  },

  // --- KIDS ---
  {
    id: "prod-9",
    name: "Embroidered Kurta Pyjama Set for Boys",
    slug: "boys-embroidered-kurta-pyjama-set",
    description: "Festive cotton silk kurta pyjama set with subtle thread embroidery and soft lining.",
    longDescription:
      "Crafted with utmost care for sensitive young skin. Features soft cotton-silk fabric, non-itchy flat embroidery on the collar and chest, and easy drawstring pyjamas.",
    category: "kids",
    subcategory: "Boys Festive",
    price: 2999,
    compare_price: 3999,
    images: [
      "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["2-3 Y", "4-5 Y", "6-7 Y", "8-9 Y", "10-11 Y"],
    colors: [
      { name: "Warm Gold", hex: "#C8964E" },
      { name: "Cream", hex: "#FFF8F0" },
      { name: "Burgundy", hex: "#7C1D3E" },
    ],
    in_stock: true,
    stock_count: 22,
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    rating: 4.9,
    reviewCount: 29,
    details: [
      "Soft 100% mulmul cotton lining to prevent itching",
      "Easy front button closure for effortless dressing",
      "Elasticated waistband on trousers for all-day comfort",
    ],
    fabric_care: ["Cotton Silk blend", "Gentle wash cold", "Low iron"],
    sku: "RG-KID-BOY-009",
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod-10",
    name: "Girls Festive Jacquard Lehenga Choli",
    slug: "girls-festive-jacquard-lehenga",
    description: "Lightweight woven jacquard lehenga choli with soft net dupatta designed for joyful twirling.",
    longDescription:
      "Made for mini celebrations and dance performances! The jacquard skirt has a gentle flare with gold brocade work, comfortable cotton lining, and a soft embroidered crop choli top.",
    category: "kids",
    subcategory: "Girls Festive",
    price: 4499,
    compare_price: 5999,
    images: [
      "https://images.unsplash.com/photo-1621786030684-4c84770adcfb?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["3-4 Y", "5-6 Y", "7-8 Y", "9-10 Y", "11-12 Y"],
    colors: [
      { name: "Coral Gold", hex: "#F39C12" },
      { name: "Deep Ruby", hex: "#7C1D3E" },
      { name: "Mint Green", hex: "#A3E4D7" },
    ],
    in_stock: true,
    stock_count: 19,
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    rating: 4.8,
    reviewCount: 34,
    details: [
      "Super lightweight and skin-friendly construction",
      "Elasticated adjustable waistband on lehenga",
      "Back zip closure on choli top with cotton backing",
      "Pre-stitched pleat drape on lightweight dupatta",
    ],
    fabric_care: ["Brocade Jacquard with Cotton lining", "Dry clean recommended"],
    sku: "RG-KID-GRL-010",
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod-11",
    name: "Boys Velvet Tuxedo Jacket & Trousers",
    slug: "boys-velvet-tuxedo-jacket-set",
    description: "Rich burgundy velvet party blazer with satin shawl collar and formal tailored trousers.",
    longDescription:
      "The perfect dapper outfit for parties and receptions. Crafted in rich jewel-tone velvet with satin lapel details and matching trousers.",
    category: "kids",
    subcategory: "Boys Festive",
    price: 5499,
    compare_price: 6999,
    images: [
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["4-5 Y", "6-7 Y", "8-9 Y", "10-11 Y"],
    colors: [
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Royal Blue", hex: "#1B4F72" },
    ],
    in_stock: true,
    stock_count: 11,
    featured: false,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.9,
    reviewCount: 16,
    details: [
      "Satin shawl collar and welt flap pockets",
      "Single button front fastening",
      "Includes adjustable formal trousers",
    ],
    fabric_care: ["Micro Velvet", "Dry clean only"],
    sku: "RG-KID-BOY-011",
    created_at: "2026-02-18T00:00:00.000Z",
  },
  {
    id: "prod-12",
    name: "Girls Chanderi Silk Peplum Sharara Set",
    slug: "girls-chanderi-silk-sharara-set",
    description: "Twirl-worthy peplum kurti with flared tiered sharara and gota patti lace border.",
    longDescription:
      "Modern yet traditional, this peplum sharara set combines playful movement with royal elegance for festive pujas and sangeet nights.",
    category: "kids",
    subcategory: "Girls Festive",
    price: 3899,
    compare_price: 4999,
    images: [
      "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1621786030684-4c84770adcfb?auto=format&fit=crop&w=900&q=80",
    ],
    sizes: ["3-4 Y", "5-6 Y", "7-8 Y", "9-10 Y"],
    colors: [
      { name: "Sunlit Yellow", hex: "#F4D03F" },
      { name: "Burgundy", hex: "#7C1D3E" },
      { name: "Powder Blue", hex: "#AED6F1" },
    ],
    in_stock: true,
    stock_count: 16,
    featured: false,
    isBestSeller: false,
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 21,
    details: [
      "Tiered flared sharara with comfortable elastic waist",
      "Peplum flared kurti with handmade potli buttons",
      "Matching lightweight chiffon dupatta with gota border",
    ],
    fabric_care: ["Chanderi Silk with 100% Cotton lining", "Dry clean or gentle hand wash"],
    sku: "RG-KID-GRL-012",
    created_at: "2026-02-15T00:00:00.000Z",
  },
];

export const MOCK_REVIEWS = [
  {
    id: "rev-1",
    name: "Aarav Sharma",
    city: "New Delhi",
    rating: 5,
    comment: "The velvet sherwani quality surpassed all my expectations. The fit was bespoke perfection!",
    productName: "Royal Velvet Sherwani",
  },
  {
    id: "rev-2",
    name: "Priyanka Mehta",
    city: "Mumbai",
    rating: 5,
    comment: "Stunning Banarasi silk saree. The zari work is authentic and the fabric drape feels pure luxury.",
    productName: "Banarasi Silk Saree",
  },
  {
    id: "rev-3",
    name: "Vikram Singhania",
    city: "Jaipur",
    rating: 5,
    comment: "Raghav Garments sets a benchmark for Indian luxury fashion. Super fast delivery and premium packaging.",
    productName: "Classic Linen Shirt",
  },
];
