-- =========================================================
-- RAGHAV GARMENTS — Supabase Seed Data
-- Initial Products Catalog
-- =========================================================

insert into public.products (
  id, name, slug, description, long_description, category, subcategory, price, compare_price, images, sizes, colors, in_stock, stock_count, featured, is_best_seller, is_new_arrival, rating, review_count, details, fabric_care, sku
) values
(
  'prod-1',
  'Royal Velvet Embroidered Sherwani',
  'royal-velvet-embroidered-sherwani',
  'Handcrafted burgundy velvet sherwani with intricate zardozi work and silk lining.',
  'Crafted from plush micro-velvet, this regal sherwani features heritage zardozi needlework along the mandarin collar, cuffs, and button placket. Tailored for grand celebrations and weddings, it includes a tailored churidar and pocket square.',
  'men',
  'Ethnic Wear',
  14999.00,
  19999.00,
  array['https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80'],
  array['38', '40', '42', '44', '46'],
  '[{"name": "Burgundy", "hex": "#7C1D3E"}, {"name": "Antique Gold", "hex": "#C8964E"}, {"name": "Midnight Black", "hex": "#1A1A1A"}]'::jsonb,
  true,
  15,
  true,
  true,
  false,
  4.9,
  38,
  array['Intricate hand-embroidered zardozi and dabka work', 'Concealed button closure with ornate metallic buttons', 'Structured shoulder pads for a sharp, royal silhouette', 'Accompanied by a matching churidar in dupion silk'],
  array['Fabric: 100% Micro Velvet; Inner: 100% Cotton Silk', 'Professional dry clean only', 'Do not steam iron embroidery directly', 'Store in breathable garment bag'],
  'RG-MEN-SHW-001'
),
(
  'prod-2',
  'Classic Linen Tailored Kurta Shirt',
  'classic-linen-tailored-kurta-shirt',
  'Breathable European flax linen casual short kurta shirt with mother-of-pearl buttons.',
  'A modern blend of classic Indian short kurta aesthetics with European linen refinement. Perfectly tailored with a contemporary mandarin collar and curved hem for effortless elegance from day events to evening gatherings.',
  'men',
  'Casual Shirts',
  3499.00,
  4499.00,
  array['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80'],
  array['S', 'M', 'L', 'XL', 'XXL'],
  '[{"name": "Warm Sand", "hex": "#D2B48C"}, {"name": "Burgundy", "hex": "#7C1D3E"}, {"name": "Off White", "hex": "#F8F9FA"}]'::jsonb,
  true,
  35,
  false,
  true,
  true,
  4.8,
  42,
  array['100% pre-washed French linen for supreme softness', 'Genuine mother-of-pearl buttons', 'Band collar with 4-button placket', 'Side slits for easy movement'],
  array['100% Linen', 'Gentle machine wash cold with similar colors', 'Warm iron while damp for crisp finish', 'Line dry in shade'],
  'RG-MEN-LIN-002'
),
(
  'prod-5',
  'Handwoven Banarasi Katan Silk Saree',
  'handwoven-banarasi-silk-saree',
  'Pure katan silk saree woven with real gold zari floral motifs and a rich heritage pallu.',
  'Handcrafted over 45 days by master weavers in Varanasi, this heirloom saree features intricate jaal work with gold zari intertwining across pure mulberry katan silk. Comes with unstitched blouse piece.',
  'women',
  'Sarees',
  18499.00,
  24999.00,
  array['https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80'],
  array['Free Size (5.5m + 0.8m Blouse)'],
  '[{"name": "Crimson Red", "hex": "#9E1B32"}, {"name": "Burgundy", "hex": "#7C1D3E"}, {"name": "Royal Emerald", "hex": "#0B5345"}]'::jsonb,
  true,
  8,
  true,
  true,
  false,
  4.9,
  56,
  array['Authentic Varanasi Handloom Mark certified', 'Pure Katan Silk with kadwa gold zari weave', 'Includes matching unstitched blouse fabric (80 cm)', 'Heirloom finish with hand-twisted tassels'],
  array['100% Pure Katan Silk', 'Dry clean only', 'Store wrapped in pure cotton muslin cloth', 'Refold periodically to prevent crease wear'],
  'RG-WMN-SAR-005'
),
(
  'prod-6',
  'Chanderi Floral Anarkali Suit Set',
  'chanderi-floral-anarkali-suit',
  'Graceful Chanderi silk Anarkali suit with organza dupatta and gota patti detailing.',
  'A vision in pastel poetry, this flared Chanderi Anarkali features hand-block floral prints accented with delicate gold gota patti and sequins. Paired with comfortable churidar pants and a sheer scalloped organza dupatta.',
  'women',
  'Suits & Sets',
  9999.00,
  12999.00,
  array['https://images.unsplash.com/photo-1583391733975-009214734316?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80'],
  array['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  '[{"name": "Blush Rose", "hex": "#E8A598"}, {"name": "Burgundy", "hex": "#7C1D3E"}, {"name": "Sage Green", "hex": "#87A96B"}]'::jsonb,
  true,
  14,
  true,
  true,
  true,
  4.8,
  31,
  array['24-kali flared Anarkali silhouette with full cotton lining', 'Scalloped hand-embroidered organza dupatta (2.5m)', 'Comfortable elasticated waistband churidar pants', 'Keyhole back neck with handcrafted latkan tassels'],
  array['Kurta: Chanderi Silk; Lining: 100% Mulmul Cotton', 'Dupatta: Pure Organza', 'Dry clean only'],
  'RG-WMN-ANK-006'
),
(
  'prod-9',
  'Embroidered Kurta Pyjama Set for Boys',
  'boys-embroidered-kurta-pyjama-set',
  'Festive cotton silk kurta pyjama set with subtle thread embroidery and soft lining.',
  'Crafted with utmost care for sensitive young skin. Features soft cotton-silk fabric, non-itchy flat embroidery on the collar and chest, and easy drawstring pyjamas.',
  'kids',
  'Boys Festive',
  2999.00,
  3999.00,
  array['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=900&q=80'],
  array['2-3 Y', '4-5 Y', '6-7 Y', '8-9 Y', '10-11 Y'],
  '[{"name": "Warm Gold", "hex": "#C8964E"}, {"name": "Cream", "hex": "#FFF8F0"}, {"name": "Burgundy", "hex": "#7C1D3E"}]'::jsonb,
  true,
  22,
  true,
  true,
  false,
  4.9,
  29,
  array['Soft 100% mulmul cotton lining to prevent itching', 'Easy front button closure for effortless dressing', 'Elasticated waistband on trousers for all-day comfort'],
  array['Cotton Silk blend', 'Gentle wash cold', 'Low iron'],
  'RG-KID-BOY-009'
)
on conflict (slug) do nothing;
